version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    ports: 
      - '8000:8000'
    command: python3 manage.py runserver
    volumes: 
      - ./:/home/app/
    depends_on: 
      - db
  db:
    image: postgres:12.6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5444:5432'
    volumes:
      - pg_data:/var/lib/postgres_data

volumes:
  pg_data:

