# Generated by Django 2.2 on 2020-08-16 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plantId_id", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProfilePlant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True, null=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plants.Plant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plant",
                    models.ManyToManyField(
                        through="plants.ProfilePlant", to="plants.Plant"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profileplant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plants.UserProfile"
            ),
        ),
        migrations.CreateModel(
            name="PlantPicture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True, null=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plants.Plant"
                    ),
                ),
                (
                    "profile_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.ProfilePlant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Annual", "Annual"),
                            ("Biennial", "Biennial"),
                            ("Perennial", "Perennial"),
                        ],
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "growth_habit",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "growth_rate",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "average_height",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "maximum_height",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "toxicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("None", "None"),
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("sowing", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "ph_maximum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "ph_minimum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("light", models.IntegerField(blank=True, null=True)),
                ("atmospheric_humidity", models.IntegerField(blank=True, null=True)),
                (
                    "growth_months",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "bloom_months",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "fruit_months",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "minimum_precipitation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "maximum_precipitation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "minimum_temperature",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("soil_nutriments", models.IntegerField(blank=True, null=True)),
                ("soil_salinity", models.IntegerField(blank=True, null=True)),
                ("soil_texture", models.IntegerField(blank=True, null=True)),
                ("soil_humidity", models.IntegerField(blank=True, null=True)),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="plants.Plant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommonName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plants.Plant"
                    ),
                ),
            ],
        ),
    ]
