# Generated by Django 2.2 on 2020-08-27 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonname',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_names', to='plants.Plant'),
        ),
        migrations.AlterField(
            model_name='description',
            name='atmospheric_humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='duration',
            field=models.CharField(blank=True, choices=[('Annual', 'Annual'), ('Biennial', 'Biennial'), ('Perennial', 'Perennial')], max_length=2),
        ),
        migrations.AlterField(
            model_name='description',
            name='toxicity',
            field=models.CharField(blank=True, choices=[('Zero', 'Zero'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Zero', max_length=6),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=stdimage.models.StdImageField(upload_to=dynamic_filenames.FilePattern(filename_pattern='plant_{uuid:base64}{ext}')),
        ),
        migrations.AlterField(
            model_name='profileplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_profiles', to='plants.Plant'),
        ),
        migrations.AlterField(
            model_name='profileplant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plant_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
