# Generated by Django 2.2 on 2020-08-17 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("internal_id", models.IntegerField()),
                ("external_id", models.IntegerField()),
            ],
            options={"abstract": False},
        ),
        migrations.RemoveField(model_name="userprofile", name="plant"),
        migrations.RemoveField(model_name="userprofile", name="user"),
        migrations.RemoveField(model_name="plant", name="plantId_id"),
        migrations.RemoveField(model_name="profileplant", name="update"),
        migrations.AddField(
            model_name="commonname",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="commonname",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="description",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="description",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="plant",
            field=models.ManyToManyField(
                through="plants.ProfilePlant", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profileplant",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AlterField(
            model_name="commonname",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="common_name",
                to="plants.Plant",
            ),
        ),
        migrations.AlterField(
            model_name="description",
            name="atmospheric_humidity",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="average_height",
            field=models.CharField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="bloom_months",
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="duration",
            field=models.CharField(
                blank=True,
                choices=[("AL", "Annual"), ("BL", "Biennial"), ("PL", "Perennial")],
                default=1,
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="fruit_months",
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="growth_habit",
            field=models.CharField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="growth_months",
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="growth_rate",
            field=models.CharField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="maximum_height",
            field=models.CharField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="maximum_precipitation",
            field=models.CharField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="minimum_precipitation",
            field=models.CharField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="minimum_temperature",
            field=models.CharField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="toxicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO", "Annual"),
                    ("LO", "Low"),
                    ("MD", "Medium"),
                    ("HI", "High"),
                ],
                default="NO",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="profileplant",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="profileplant",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plant_profile",
                to="plants.Plant",
            ),
        ),
        migrations.AlterField(
            model_name="profileplant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_plant_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="PlantPicture"),
        migrations.DeleteModel(name="UserProfile"),
        migrations.AddField(
            model_name="picture",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plants.Plant"
            ),
        ),
        migrations.AddField(
            model_name="picture",
            name="profile_plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plants.ProfilePlant"
            ),
        ),
    ]
