# Generated by Django 2.2 on 2020-08-27 13:31

from django.db import migrations
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20200827_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=stdimage.models.StdImageField(upload_to=dynamic_filenames.FilePattern(filename_pattern='/media/plant_{uuid:base64}{ext}')),
        ),
    ]
