# Generated by Django 2.2 on 2020-08-17 23:03

from django.db import migrations, models
import django.db.models.deletion
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [("plants", "0002_auto_20200817_2201")]

    operations = [
        migrations.RemoveField(model_name="description", name="created"),
        migrations.RemoveField(model_name="description", name="modified"),
        migrations.AlterField(
            model_name="picture",
            name="image",
            field=stdimage.models.StdImageField(
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}"
                )
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="plants.Plant",
            ),
        ),
    ]
