# Generated by Django 2.2 on 2020-09-07 18:38

from django.db import migrations
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20200827_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='profile_plant',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=stdimage.models.StdImageField(upload_to=dynamic_filenames.FilePattern(filename_pattern='/plant_{uuid:base64}{ext}')),
        ),
    ]
